apiVersion: v2
name: harness
version: 0.1.0
appVersion: "76324"
description: A Helm chart for Harness Community Edition.

type: application
home: https://harness.io/
sources:
  - https://github.com/harness
  - https://github.com/harness/harness-core
  - https://github.com/harness/harness-core-ui