apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-auth-ui
  annotations:
    {{- toYaml .Values.configMap.annotations | nindent 4 }}
  labels:
    {{- include "harness.configMap.labels" . | nindent 4 }}
data:
  DEPLOYMENT_TYPE: COMMUNITY

---

apiVersion: v1
kind: Service
metadata:
  name: ng-auth-ui
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "harness.service.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ng-auth-ui

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-auth-ui
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    app: ng-auth-ui
    {{- include "harness.deployment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ng-auth-ui
  template:
    metadata:
      annotations:
        {{- toYaml .Values.replica.annotations | nindent 8 }}
      labels:
        app: ng-auth-ui
        {{- include "harness.replica.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness.serviceAccountName" . }}
      containers:
      - name: ng-auth-ui
        image: harness/ng-auth-ui-signed:{{ .Values.versions.ng_auth_ui }}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 65534
          runAsNonRoot: true
        readinessProbe:
          httpGet:
            path: /health
            port: ng-auth-ui-port
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: ng-auth-ui-port
          initialDelaySeconds: 90
          periodSeconds: 20
          failureThreshold: 2
        ports:
        - name: ng-auth-ui-port
          containerPort: 8080
          protocol: "TCP"
        envFrom:
        - configMapRef:
            name: ng-auth-ui
        resources:
          limits:
            memory: {{ .Values.ng_auth_ui.resources.limits.memory }}
            cpu: {{ .Values.ng_auth_ui.resources.limits.cpu }}
          requests:
            memory: {{ .Values.ng_auth_ui.resources.requests.memory }}
            cpu: {{ .Values.ng_auth_ui.resources.requests.cpu }}
