apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
  annotations:
    {{- toYaml .Values.configMap.annotations | nindent 4 }}
  labels:
    {{- include "harness.configMap.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes 1;
    pid /tmp/nginx.pid;

    events { worker_connections 1024; }

    http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;
        sendfile on;

        upstream manager_service {
            server manager:9090;
        }

        upstream manager_service_grpc {
            server manager:9879;
        }

        upstream ng_manager_service {
            server ng-manager:7090;
        }

        upstream pipeline_service {
            server pipeline-service:12001;
        }

        upstream platform_service {
            server platform-service:9005;
        }

        upstream log_service {
            server log-service:8079;
        }

        upstream ng_ui_service {
            server ng-ui:8080;
        }

        upstream ng_auth_ui_service {
            server ng-auth-ui:8080;
        }

        upstream delegate_proxy_service {
            server delegate-proxy:8080;
        }

        server {
            listen 9879 http2;

            location / {
                grpc_pass grpc://manager_service_grpc ;
            }
        }

        server {
            listen 80 default_server;

            location / {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;

                proxy_pass http://ng_auth_ui_service/;
            }

            location /auth/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;

                proxy_pass http://ng_auth_ui_service/;
            }

            location /storage/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://delegate_proxy_service/storage/;
            }

            location /api/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://manager_service/api/;
            }

            location /stream/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://manager_service/stream/;
            }

            location /ng/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://ng_ui_service/;
            }

            location /ng/api/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://ng_manager_service/;
            }

            location /pipeline/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://pipeline_service/;
            }

            location /audit/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://platform_service/;
            }

            location /notifications/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://platform_service/;
            }

            location /resourcegroup/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://platform_service/;
            }

            location /log-service/ {
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                client_max_body_size 2G;
                proxy_pass http://log_service/;
            }
        }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: proxy
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "harness.service.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - name: http
      port: 80
    - name: grpc
      port: 9879

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  labels:
    {{- include "harness.deployment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      annotations:
        {{- toYaml .Values.replica.annotations | nindent 8 }}
      labels:
        app: proxy
        {{- include "harness.replica.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harness.serviceAccountName" . }}
      containers:
        - name: proxy
          image: harness/nginx:{{ .Values.versions.nginx }}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9879
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            limits:
              memory: {{ .Values.proxy.resources.limits.memory }}
              cpu: {{ .Values.proxy.resources.limits.cpu }}
            requests:
              memory: {{ .Values.proxy.resources.requests.memory }}
              cpu: {{ .Values.proxy.resources.requests.cpu }}
      volumes:
        - name: nginx-config
          configMap:
            name: proxy
